export const projects = [
  {
    id: 1,
    title: "Buscador de Perfil GitHub",
    description: "Aplicação para buscar e exibir perfis do GitHub de forma rápida e responsiva.",
    longDescription: "Permite pesquisar qualquer usuário do GitHub e visualizar informações públicas do perfil, repositórios e estatísticas.",
    image: "/buscador-github.png",
    technologies: ["React", "Vite", "TypeScript", "Tailwind CSS", "GitHub API"],
    github: "https://github.com/AndersonJr-Dev/buscador-de-perfil-github",
    demo: "",
    category: "Frontend",
    featured: false,
  },
  {
    id: 2,
    title: "Teste Técnico Innovation Class",
    description: "Projeto de teste técnico com funcionalidades de cadastro, listagem e exclusão de usuários.",
    longDescription: "Desenvolvido para avaliação técnica, inclui CRUD completo, validação de formulários e layout responsivo.",
    image: "/teste-innovation-class.png",
    technologies: ["React", "Vite", "TypeScript", "Tailwind CSS"],
    github: "https://github.com/AndersonJr-Dev/teste-tecnico-innovation-class",
    demo: "",
    category: "Frontend",
    featured: false,
  },
  {
    id: 3,
    title: "Projeto Tarefas FastAPI",
    description: "API de tarefas desenvolvida com FastAPI, Python e SQLite.",
    longDescription: "Backend para gerenciamento de tarefas, com endpoints RESTful, autenticação JWT e documentação automática.",
    image: "/tarefas-fastapi2.png",
    technologies: ["Python", "FastAPI", "SQLite", "JWT"],
    github: "https://github.com/AndersonJr-Dev/projeto_tarefas_fastapi",
    demo: "",
    category: "Backend",
    featured: false,
  },
  {
    id: 4,
    title: "Projeto App Feira de Trocas (TrocAi)",
    description: "Uma aplicação full-stack para troca de itens usados em uma comunidade local.",
    longDescription: "TrocAi é uma plataforma que permite aos usuários de uma comunidade local registrar e trocar itens usados, como livros, roupas, brinquedos e eletrônicos, promovendo o consumo consciente e fortalecendo os laços comunitários.",
    image: "/app-feira-trocas.png",
    technologies: ["ReactJS", "Node.js", "Express", "Prisma ORM", "PostgreSQL"],
    github: "https://github.com/AndersonJr-Dev/app-feira-de-trocas",
    demo: "",
    category: "Fullstack",
    featured: true,
  },
  {
    id: 5,
    title: "Projeto SitePrótetico",
    description: "Site institucional para uma clínica de prótese dentária.",
    longDescription: "Desenvolvido um site institucional para uma clínica de prótese dentária, apresentando serviços, equipe e informações de contato de forma clara e atraente.",
    image: "/site-protetico.png",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Vite"],
    github: "https://github.com/AndersonJr-Dev/SiteProtetico/tree/main",
    demo: "https://helsonprotetico.vercel.app/",
    category: "Frontend",
    featured: false,
  },
  {
    id: 6,
    title: "Projeto ImagePress",
    description: "Aplicativo de desktop Electron para otimizar imagens arrastadas (JPG/PNG)",
    longDescription: "ImagePress é um aplicativo de desktop desenvolvido com Electron que permite aos usuários otimizar imagens arrastando e soltando arquivos JPG ou PNG na interface. O aplicativo reduz o tamanho dos arquivos de imagem sem comprometer significativamente a qualidade, facilitando o compartilhamento e armazenamento.",
    image: "/imagepress.png",
    technologies: ["Electron", "Node.js", "JavaScript", "Sharp"],
    github: "https://github.com/AndersonJr-Dev/imagepress",
    demo: "",
    category: "Fullstack",
    featured: false,
  },
  {
    id: 7,
    title: "Projeto Buscador de Vulnerabilidades",
    description: "Um programa para busca de vulnerabilidades em sistemas web, desenvolvido para profissionais de segurança e participantes de programas de bug bounty.",
    longDescription: "Este projeto é uma ferramenta de linha de comando desenvolvida em Python que permite aos usuários buscar vulnerabilidades comuns em sistemas web. Com uma interface simples, o programa realiza varreduras automatizadas para identificar falhas de segurança, auxiliando profissionais de segurança e entusiastas de bug bounty a protegerem suas aplicações.",
    image: "/buscador-vulnerabilidades.png",
    technologies: ["Python"],
    github: "https://github.com/AndersonJr-Dev/Buscador-Vulnerabilidades",
    demo: "",
    category: "Backend",
    featured: false,
  },
  {
    id: 8,
    title: "Pilops - Histórico de Voos",
    description: "Projeto full-stack com frontend e API para histórico de voos.",
    longDescription:
      "Frontend em React/Vite e backend em Node/Express/TypeScript que servem um histórico de voos com transformação de dados. O frontend consome a API e apresenta lista e detalhes de voos seguindo design do Figma.",
    image: "/teste-pilops.png",
    technologies: ["React", "Node.js", "Express", "TypeScript"],
    github: "https://github.com/AndersonJr-Dev/pilops-backend",
    demo: "https://teste-pilops.vercel.app/",
    category: "Fullstack",
    featured: false,
  },
  {
    id: 9,
    title: "Cardápio Digital",
    description: "Cardápio digital interativo para restaurante com pedidos via WhatsApp.",
    longDescription: "Sistema completo de cardápio digital com carrinho de compras, cálculo de total e envio de pedidos formatados diretamente para o WhatsApp do estabelecimento.",
    image: "/cardapio-rb.png",
    technologies: ["React", "Typescript", "Vite", "Tailwind CSS", "Shadcn/ui"],
    github: "https://github.com/AndersonJr-Dev/cardapio-rb",
    demo: "",
    category: "Frontend",
    featured: true,
  },
  {
    id: 10,
    title: "Reserve-Me - Sistema de Reservas",
    description: "Plataforma de agendamento de serviços para barbearias e salões.",
    longDescription: "Sistema fullstack para gestão de agendamentos com autenticação de usuários, painel administrativo, seleção de horários e serviços. Inclui validações de disponibilidade e histórico de agendamentos.",
    image: "/reserve-me.png",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Tailwind CSS"],
    github: "https://github.com/AndersonJr-Dev/reserve-me-saas",
    demo: "https://reserve-me-online.vercel.app/",
    category: "Fullstack",
    featured: true,
  }
]
